{
 "title": "Conta",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "API Access",
   "type": "graph",
   "description": "Total number of API Access",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "box_api{group=\"api\",instance=\"box-api:3443\",job=\"box-exporter\"}",
     "legendFormat": "{{method}} {{path}} {{statusCode}}"
    }
   ]
  },
  {
   "title": "MongoDB Status",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "up{group=\"db1\",instance=\"mongodb-exporter:9001\",job=\"mongodb-exporter\"}"
    }
   ]
  },
  {
   "title": "Connections Current",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "mongodb_connections{group=\"db1\",instance=\"mongodb-exporter:9001\",job=\"mongodb-exporter\",state=\"current\"}",
     "legendFormat": "Connections Current"
    }
   ]
  },
  {
   "title": "Connections Available",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "mongodb_connections{group=\"db1\",instance=\"mongodb-exporter:9001\",job=\"mongodb-exporter\",state=\"available\"}",
     "legendFormat": "Connections Available"
    }
   ]
  },
  {
   "title": "Documents",
   "type": "graph",
   "description": "Total number of documents",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "none", "label": "Quatidade" }
   ],
   "targets": [
    {
     "expr": "mongodb_metrics_document_total{group=\"db1\",instance=\"mongodb-exporter:9001\",job=\"mongodb-exporter\",state=\"inserted\"}",
     "legendFormat": "inserted"
    },
    {
     "expr": "mongodb_metrics_document_total{group=\"db1\",instance=\"mongodb-exporter:9001\",job=\"mongodb-exporter\",state=\"updated\"}",
     "legendFormat": "updated"
    },
    {
     "expr": "mongodb_metrics_document_total{group=\"db1\",instance=\"mongodb-exporter:9001\",job=\"mongodb-exporter\",state=\"returned\"}",
     "legendFormat": "returned"
    },
    {
     "expr": "mongodb_metrics_document_total{group=\"db1\",instance=\"mongodb-exporter:9001\",job=\"mongodb-exporter\",state=\"deleted\"}",
     "legendFormat": "deleted"
    }
   ]
  },
  {
   "title": "NoSQL Operation",
   "type": "graph",
   "description": "Total number of NoSQL operations",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 4 },
   "yaxes": [
    { "format": "none", "label": "Quatidade" }
   ],
   "targets": [
    {
     "expr": "mongodb_op_counters_total{group=\"db1\",instance=\"mongodb-exporter:9001\",job=\"mongodb-exporter\",type=\"delete\"}",
     "legendFormat": "delete"
    },
    {
     "expr": "mongodb_op_counters_total{group=\"db1\",instance=\"mongodb-exporter:9001\",job=\"mongodb-exporter\",type=\"getmore\"}",
     "legendFormat": "get more"
    },
    {
     "expr": "mongodb_op_counters_total{group=\"db1\",instance=\"mongodb-exporter:9001\",job=\"mongodb-exporter\",type=\"insert\"}",
     "legendFormat": "insert"
    },
    {
     "expr": "mongodb_op_counters_total{group=\"db1\",instance=\"mongodb-exporter:9001\",job=\"mongodb-exporter\",type=\"query\"}",
     "legendFormat": "query"
    },
    {
     "expr": "mongodb_op_counters_total{group=\"db1\",instance=\"mongodb-exporter:9001\",job=\"mongodb-exporter\",type=\"update\"}",
     "legendFormat": "update"
    }
   ]
  },
  {
   "title": "API Access",
   "type": "graph",
   "description": "Total number of API Access",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "box_api{group=\"api\",instance=\"box-api:3443\",job=\"box-exporter\"}",
     "legendFormat": "{{method}} {{path}} {{statusCode}}"
    }
   ]
  },
  {
   "title": "Access",
   "type": "singlestat",
   "description": "Total number of API accesses",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 13 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(box_api{group=\"api\",instance=\"box-api:3443\",job=\"box-exporter\"})"
    }
   ]
  }
 ]
}